# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6518b39899bdb46791575ee07dc786d7"
application_url = "https://shopping-walked-though-anyway.trycloudflare.com"
embedded = true
name = "KAS040 - Discount Manager"
handle = "kas040-discount-manager"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_product_listings"

[auth]
redirect_urls = [
  "https://shopping-walked-though-anyway.trycloudflare.com/auth/callback",
  "https://shopping-walked-though-anyway.trycloudflare.com/auth/shopify/callback",
  "https://shopping-walked-though-anyway.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "red-devil-essentials-1-1.myshopify.com"
automatically_update_urls_on_dev = true
